"""Initial production schema baseline

Revision ID: d2964dc9ce17
Revises: 
Create Date: 2025-06-26 11:11:00.046616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2964dc9ce17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_employees_department'), table_name='employees')
    op.drop_index(op.f('idx_machine_faults_date'), table_name='machine_faults')
    op.drop_index(op.f('idx_machine_faults_machine_id'), table_name='machine_faults')
    op.drop_index(op.f('idx_machine_faults_severity'), table_name='machine_faults')
    op.drop_index(op.f('idx_machines_status'), table_name='machines')
    op.drop_index(op.f('idx_orders_status'), table_name='orders')
    op.drop_index(op.f('idx_products_category'), table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('idx_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('idx_machines_status'), 'machines', ['status'], unique=False)
    op.create_index(op.f('idx_machine_faults_severity'), 'machine_faults', ['severity'], unique=False)
    op.create_index(op.f('idx_machine_faults_machine_id'), 'machine_faults', ['machine_id'], unique=False)
    op.create_index(op.f('idx_machine_faults_date'), 'machine_faults', ['fault_date'], unique=False)
    op.create_index(op.f('idx_employees_department'), 'employees', ['department'], unique=False)
    # ### end Alembic commands ###
